# -*- coding: utf-8 -*-
{% set slug = cookiecutter.project_slug %}
#
# {{ cookiecutter.project_name }} documentation build configuration file.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

from collections import OrderedDict
import sys
import os
import datetime as dt

import alabaster
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('..'))
import {{ slug }} # flake8: noqa

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'alabaster',
]

primary_domain = 'py'
default_role = 'py:obj'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'
# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'my project'
copyright = ' {0:%Y} <a href="{{ cookiecutter.organisation_url }}">{{ cookiecutter.organisation }}</a>'.format(
    dt.datetime.utcnow()
)

version = release = {{ slug }}.__version__

exclude_patterns = ['_build']

# THEME

html_theme_path = [alabaster.get_path()]
html_theme = 'alabaster'
html_static_path = ['_static']
templates_path = ['_templates']
html_show_sourcelink = False

html_theme_options = {
    'logo': 'logo.png',
    'description': '{{ cookiecutter.project_name }}',
    'description_font_style': 'italic',
    'code_font_size': '0.8em',
    'warn_bg': '#FFC',
    'warn_border': '#EEE',
}

html_sidebars = {
    'index': [
        'about.html', 'searchbox.html',
    ],
    '**': ['about.html',
           'localtoc.html', 'relations.html', 'searchbox.html']
}
