version: "3.7"
services:
  {{ cookiecutter.project_slug }}:
    image: jupyter/all-spark-notebook:latest
    ports:
    - "8888:8888/tcp"
    - "4040:4040/tcp"
    networks:
    - {{ cookiecutter.project_slug }}_network
    working_dir: /home/$USER/
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
    volumes:
      - .:/home/$USER/

networks:
  {{ cookiecutter.project_slug }}_network:
